service: serverless-fastapi-playwright

frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  profile: serverless-fastapi-playwright
  region: ${env:AWS_REGION, "us-east-1"}
  ecr:
    images:
      app:
        path: ./
        platform: linux/amd64
  stackTags:
    Application: serverless-fastapi-playwright
    Environment: dev

    Managed-By: serverless
functions:
  app:
    image:
      name: app
    url: true
    memorySize: 2048
    timeout: 60

plugins:
  - serverless-plugin-resource-tagging
